name: CI - Build & Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/dhsilveira/youtube-whisper-transcriber:latest
          context: .

      - name: Run container (smoke test)
        run: |
          docker run --rm -e INPUT_URL="https://www.youtube.com/watch?v=EXEMPLO" ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
